version: "3.7"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
    ports: 
      - 3307:3306
    volumes: 
      - ./db/:/var/lib/mysql
    networks: 
      - prestashop_net
  
  prestashop:
    image: prestashop/prestashop:latest
    environment:
      DB_SERVER: ${DATABASE_SERVER}
      DB_USER: ${DATABASE_USERNAME}
      DB_PASSWD: ${DATABASE_PASSWORD}
      DB_NAME: ${DATABASE_NAME}
    ports: 
      - 8080:80
    volumes: 
      - ./prestashop/:/var/www/html
    networks: 
      - prestashop_net

networks:
  prestashop_net:
    driver: bridge